import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter ,Fira_Code} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


const fira_code = Fira_Code({subsets:['latin'],variable:'--font-fira-code'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fira_code.variable,fira_code.className, "font-fira-code","bg-gradient-surface")}
    >
      <body className="min-h-full  bg-gradient-surface flex flex-col">{children}</body>
    </html>
  );
}
